pipelines:
  pipe1:
    group: sample
    materials:
      mygit:
        git: https://github.com/sgrG24/newCPPproject.git
	branch: master
    stages:
      build:
        jobs:
	  tasks:
	    - exec: 
	        command: ./a.out