#ci.gocd.yaml
format_version: 9
pipelines:
  compile-and-testing:
    group: mygroup
    materials:
      mygit:
        git: https://github.com/sgrG24/Akka-Http.git
        branch: master
    stages:
      - compiling-and-testing:
          jobs:
          running-cmd-job:
            tasks:
              exec: 
                command: ./compile
