#ci.gocd.yaml
format_version: 9
pipelines:
  compile-and-testing:
    group: mygroup
    materials:
      mygit:
        git: https://github.com/sgrG24/Akka-Http.git
        branch: master
    stages:
      - compiling-and-testing:
          tasks:
           - exec: 
              command: ./ops/compile
      - sbt-assembly:
          tasks:
           - exec:
              command: sbt
              arguments: 
               - assembly
          artifacts:
            - build:
               source: target/scala-2.12/Akka-HTTP-assembly-0.1.jar
               destination: ''
  creating-and-pushing-docker-image:
    group: mygroup
    materials:
      mygit:
        git: https://github.com/sgrG24/Akka-Http.git
        branch: master
      compile-and-testing:
        pipeline: compile-and-testing
        stage: sbt-assembly
    stages:
    - fetching-artifacts:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          fetching-artifact:
            timeout: 0
            tasks:
            - fetch:
                is_file: true
                source: Akka-HTTP-assembly-0.1.jar
                destination: ''
                pipeline: compile-and-testing
                job: sbt-assembly
                stage: sbt-assembly
                run_if: passed
            - exec:
                arguments:
                - -c
                - docker build -t sagar2405/akka-http-app:${GO_PIPELINE_LABEL} ./
                command: sh
                run_if: passed
            - exec:
                arguments:
                - images
                command: docker
                run_if: passed
            - exec:
                arguments:
                - -c
                - docker push sagar2405/akka-http-app:${GO_PIPELINE_LABEL}
                command: sh
                run_if: passed
            - exec:
                arguments:
                - -c
                - kubectl apply -f ./ops/akka-http-app-delpoyment-definition.yml
                command: sh
                run_if: passed
